#%RAML 0.8
title: 1. AM PROD API's (Live)
version: 1.0
documentation:
- title: 1. AM PROD API's (Live)
  content: These are the live API's used by the AirMarket the products on Platform.
baseUri: http://www.example.com
baseUriParameters: {}
