#%RAML 0.8
title: 1. AM PROD API's (Live)
version: 1.0
documentation:
- title: 1. AM PROD API's (Live)
  content: These are the live API's used by the AirMarket the products on Platform.
baseUri: https://dev.airmarket.io/leaflet/airwebservice/mobile/thirdpartyservice/getSFOCInfo/2A130FB6-5787-D4F9-3475-A950E747A0D3/json
baseUriParameters: {}
/:
  get:
    description: 'TODO: Add Description'
    responses: {}
    headers:
      Content-Type:
        type: string
        example: application/json
        required: true
        displayName: Content-Type
