{
  "info": {
    "_postman_id": "263823-e9fb2fe0-129f-877e-b143-a21033a4350e",
    "name": "1. AM PROD API's (Live)",
    "description": "These are the live API's used by the AirMarket the products on Platform.",
    "schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
  },
  "item": []
}